### ISSUE TITLE
make command throws error

### ISSUE THREAD

**Issue by PratimaBharti** [santoshchaurasiyacs/lwfinger-rtlwifi_new#1]
![Screenshot from 2020-06-20 19-13-53](https://user-images.githubusercontent.com/54327856/85203330-951e2300-b32a-11ea-9a9f-88fa3c79df90.png)

**Comment by PratimaBharti** [comment]
It worked after removing **struct dentry* **  from structure initialization.

**Comment by elmussol** [comment]
Make newbie. How did you accomplish that @PratimaBharti ?

**Comment by PratimaBharti** [comment]
> Make newbie. How did you accomplish that @PratimaBharti ?

It worked after removing struct dentry *debugfsdir from static void *rtl_rate_alloc(struct ieee80211_hw *hw, struct dentry *debugfsdir) in rc.c .

**Comment by elmussol** [comment]
Thank you so much. I now have functioning wifi :-)
