### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by codiecher** [santoshchaurasiyacs/lwfinger-rtlwifi_new#4]
![image](https://user-images.githubusercontent.com/49608838/124058850-bc8aee00-da5c-11eb-8dc9-61ab920911ff.png)

I want to use the RTL8821AE driver.
after cd into the folder and 'make' the error above is returned

**Comment by codiecher** [comment]
had to reinstall it 5 more times added to the 3 times I did before this post.

**Comment by Eolien55** [comment]
Could you explain how you fixed that issue ? I am facing the same problem, and i would like to have working wifi.

**Comment by codiecher** [comment]
I actually just kept reinstalling it, I imagine it was me fkng up with the installation process. Anyways, after I installed the drivers it  still didn't  help with my wifi speed so I just got an external usb wifi adapter
